<?php
/**
 *
Used to conceal the ability to assign the administrator role by users with roles that are less than administrator. This is a band-aid to address the issue that will be solved by the full port of the role delegation module, and should be removed once that has been completed.
 *
 **/
function adap_role_concealer() {
  global $user;
  $path = $_SERVER['REQUEST_URI'];
  $finduser = 'user';
  $findpeople = 'people';
  $edit_users = strpos($path, $finduser);
  $list_users = strpos($path, $findpeople);
  if ( $user->roles !== array('authenticated', 'administrator') && (( $edit_users !== false ) || ( $list_users !== false ) ) ) { 
    backdrop_add_css('modules/adap_role/css/not_admin.css');
  }
  else {
	  
  }  
}
adap_role_concealer();

function adap_admin_role_concealer() {
  global $user;
  $path = $_SERVER['REQUEST_URI'];
  $finduser = 'user';
  $findpeople = 'people';
  $edit_users = strpos($path, $finduser);
  $list_users = strpos($path, $findpeople);
  if ( $user->roles !== array('authenticated', 'administrator') && $user->roles !== array('authenticated', 'adap_administrator') && (( $edit_users !== false ) || ( $list_users !== false ) ) ) {
	  backdrop_add_css('modules/adap_role/css/not_adap_admin.css');
  }
  else {
	  
  }
}
adap_admin_role_concealer();

function adap_user_menu_concealer() {
  global $user;
  if ( $user->roles !== array('authenticated', 'administrator') && $user->roles !== array('authenticated', 'adap_administrator') && $user->roles !== array('authenticated', 'manager') )  {
	  backdrop_add_css('modules/adap_role/css/not_admin_manager.css');
  }
  else {
	  
  }
}
adap_user_menu_concealer();

?>
